kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo world
- name: kaniko
  image: banzaicloud/drone-kaniko
  settings:
    username: asd
    password: Nigger123
    repo: foo/bar
    registry: demo.goharbor.io